name: Gerar PDF do Currículo

on:
  push:
    paths:
      - 'curriculo.md' # Executa a action apenas se o curriculo.md for alterado
      - '.github/workflows/gerar-pdf.yml'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      # Etapa 1: Faz o checkout do código do seu repositório
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      # Etapa 2: Instala o Pandoc no ambiente da Action
      - name: Instalar Pandoc e dependências de PDF (LaTeX)
        uses: pandoc/setup-pandoc
        with:
          # A versão 'latest' do pandoc será instalada por padrão.
          # Esta action também instala o LaTeX, necessário para a criação de PDFs.
          install-latex: true

      # Etapa 3: Cria o diretório de saída para o PDF
      - name: Criar diretório de saída
        run: mkdir -p output

      # Etapa 4: Executa o comando Pandoc para converter o arquivo
      - name: Gerar PDF com Pandoc
        run: |
          pandoc curriculo.md \
            --from markdown \
            --to pdf \
            --output output/curriculo.pdf \
            --standalone

      # Etapa 5: Faz o commit do PDF gerado de volta para o repositório
      - name: Commit do PDF
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(curriculo): atualiza curriculo.pdf"
          file_pattern: "output/curriculo.pdf"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
