name: Atualiza README
on:
  push:
    paths:
      - 'curriculo.md'
      - '.github/**'
  schedule:
    - cron: '0 0 * * 0'  # semanalmente , por exemplo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Instalar Ruby + Jekyll (local)
        run: |
          apt-get update
          apt-get install -y ruby-full build-essential zlib1g-dev
          # Instala jekyll localmente no $HOME/.gem para não precisar de permissão root
          gem install --user-install jekyll
        # Expor o diretório de gems do usuário e adicionar ao PATH
        env:
          GEM_HOME: ${{ runner.home }}/.gem
          PATH: ${{ runner.home }}/.gem/bin:${{ runner.tool_cache }}/ruby/bin:${{ env.PATH }}

      - name: Gerar README
        run: |
          jekyll build --source . --destination ./out \
            --config _config.yml,_config.readme.yml
          cp out/README.md README.md
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: Atualiza README a partir do curriculo.md" || echo "sem mudanças"
          git push
